"""empty message

Revision ID: 2b465122317e
Revises: d8aa97022ac3
Create Date: 2020-05-11 01:38:20.993399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b465122317e'
down_revision = 'd8aa97022ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.drop_constraint('shows_product_id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'Artist', ['artist_id'], ['id'])
    op.drop_column('shows', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_product_id_fkey', 'shows', 'Artist', ['product_id'], ['id'])
    op.drop_column('shows', 'artist_id')
    # ### end Alembic commands ###
